import { ServiceItem, PortfolioItem, Coupon, StoreSettings } from '@/types/store';

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    name: 'تصميم الشعارات',
    nameEn: 'Logo Design',
    nameFr: 'Création de Logo',
    description: 'شعار احترافي يعبر عن هوية علامتك التجارية',
    descriptionEn: 'Professional logo representing your brand identity',
    descriptionFr: 'Logo professionnel reflétant l’identité de votre marque',
    priceSAR: 150,
    emoji: '🎨',
    category: 'logo',
    popular: true,
    deliveryDays: 2,
  },
  {
    id: 'srv-2',
    name: 'تصميم سوشيال ميديا',
    nameEn: 'Social Media Design',
    nameFr: 'Design Réseaux Sociaux',
    description: '10 تصاميم احترافية لمنصات التواصل الاجتماعي',
    descriptionEn: '10 professional designs for social media platforms',
    descriptionFr: '10 visuels professionnels pour vos réseaux sociaux',
    priceSAR: 200,
    emoji: '📱',
    category: 'social',
    popular: false,
    deliveryDays: 3,
  },
  {
    id: 'srv-3',
    name: 'هوية بصرية كاملة',
    nameEn: 'Full Brand Identity',
    nameFr: 'Identité Visuelle Complète',
    description: 'شعار + ألوان + خطوط + بطاقات أعمال',
    descriptionEn: 'Logo + Palette + Typography + Business Cards',
    descriptionFr: 'Logo + Couleurs + Typographie + Cartes de visite',
    priceSAR: 500,
    emoji: '🖼️',
    category: 'identity',
    popular: true,
    deliveryDays: 5,
  },
  {
    id: 'srv-4',
    name: 'تصميم فيديو موشن',
    nameEn: 'Motion Graphics Video',
    nameFr: 'Vidéo Motion Design',
    description: 'فيديو موشن جرافيك مدة 30 ثانية',
    descriptionEn: '30-second high quality motion graphic video',
    descriptionFr: 'Vidéo motion design 30 secondes haute qualité',
    priceSAR: 350,
    emoji: '🎬',
    category: 'motion',
    popular: false,
    deliveryDays: 4,
  },
  {
    id: 'srv-5',
    name: 'تصميم تغليف منتجات',
    nameEn: 'Product Packaging Design',
    nameFr: 'Design d’Emballage Produit',
    description: 'تصميم عبوة احترافية لمنتجك',
    descriptionEn: 'Professional packaging box & label design',
    descriptionFr: 'Conception d’emballage et étiquette professionnelle',
    priceSAR: 400,
    emoji: '📦',
    category: 'packaging',
    popular: false,
    deliveryDays: 3,
  },
  {
    id: 'srv-6',
    name: 'تصميم موقع ويب',
    nameEn: 'Web Design UI/UX',
    nameFr: 'Design Site Web UI/UX',
    description: 'تصميم UI/UX احترافي لموقعك',
    descriptionEn: 'High-end responsive UI/UX web layout design',
    descriptionFr: 'Design d’interface web UI/UX responsive haut de gamme',
    priceSAR: 800,
    emoji: '🌐',
    category: 'web',
    popular: true,
    deliveryDays: 7,
  },
];

export const INITIAL_PORTFOLIO: PortfolioItem[] = [
  {
    id: 'port-1',
    title: 'تصميم شعار احترافي',
    titleEn: 'Logo Design Mastery',
    titleFr: 'Logo Design Élégant',
    category: 'Logo Design',
    categoryKey: 'logo',
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=1200&auto=format&fit=crop',
    description: 'شعار فاخر لشركة استشارات ملكية بأسلوب مينيملي عصري',
    tags: ['شعار', 'فاخر', 'استشارات'],
  },
  {
    id: 'port-2',
    title: 'هوية بصرية متكاملة',
    titleEn: 'Brand Identity System',
    titleFr: 'Identité Visuelle Globale',
    category: 'Brand Identity',
    categoryKey: 'identity',
    image: 'https://images.unsplash.com/photo-1600132806370-bf17e65e942f?q=80&w=1200&auto=format&fit=crop',
    description: 'هوية بصرية شاملة لعلامة عطور فاخرة تشمل الألوان والخطوط والتغليف',
    tags: ['هوية بصرية', 'عطور', 'تغليف'],
  },
  {
    id: 'port-3',
    title: 'تصاميم سوشيال ميديا',
    titleEn: 'Social Media Campaign',
    titleFr: 'Campagne Réseaux Sociaux',
    category: 'Social Media',
    categoryKey: 'social',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    description: 'حملة إعلانية مبتكرة لمنصة تسوق إلكتروني بروح عصرية جذابة',
    tags: ['سوشيال ميديا', 'إنستغرام', 'إعلانات'],
  },
  {
    id: 'port-4',
    title: 'تغليف منتجات فاخرة',
    titleEn: 'Luxury Packaging Box',
    titleFr: 'Packaging de Luxe',
    category: 'Product Packaging',
    categoryKey: 'packaging',
    image: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=1200&auto=format&fit=crop',
    description: 'تصميم صندوق تغليف منتجات العناية بالبشرة مع تفاصيل مذهبة',
    tags: ['تغليف', 'تجميل', 'ذهبي'],
  },
  {
    id: 'port-5',
    title: 'موشن جرافيك إعلاني',
    titleEn: '3D Motion Reel',
    titleFr: 'Motion Design 3D',
    category: 'Motion Graphics',
    categoryKey: 'motion',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
    description: 'مقطع موشن جرافيك مشوق لإطلاق تطبيق ذكي جديد',
    tags: ['موشن', 'فيديو', 'تطبيق'],
  },
  {
    id: 'port-6',
    title: 'واجهات متجر إلكتروني',
    titleEn: 'E-Commerce UX Platform',
    titleFr: 'Interface E-Commerce UI',
    category: 'Web Design UI/UX',
    categoryKey: 'web',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
    description: 'تصميم واجهة متجر مجوهرات فاخر تجربة مستخدم سلسة وفخمة',
    tags: ['ويب', 'UI/UX', 'متجر'],
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  { code: 'MAESTRO10', discountPercent: 10, active: true, usesCount: 14 },
  { code: 'VIP20', discountPercent: 20, active: true, usesCount: 8 },
  { code: 'GOLD50', discountPercent: 50, active: true, usesCount: 3 },
];

export const INITIAL_SETTINGS: StoreSettings = {
  whatsappNumber: '21621725094',
  adminPin: '22768061',
  storeName: 'Maestro Designs',
  snapchatHandle: 'maestro_designs',
  toptopKsaHandle: '25859934',
  bankIban: 'SA0380000000608010167519',
  bankAccountName: 'استوديو مايسترو للتصميم',
  bankName: 'البنك الأهلي السعودي (SNB)',
  sarConversionRates: {
    SAR: 1,
    AED: 0.98,
    QAR: 0.97,
    KWD: 0.082,
    USD: 0.27,
    EUR: 0.25,
  },
};
